### ISSUE TITLE
Getting an error when using nexmo.sendTTSMessage

### ISSUE THREAD

**Issue by taymoork2** [CalvertYang/simple-nexmo#3]
Hello, first off, thanks for making this plugin.
I'm getting stuck on this error, i can't tell if it's my fault, nexmo's, or a small bug in the plugin.
Please Halp

Error:
```
/test/nexmo/call has been initiated
SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (\node_modules\simple-nexmo\lib\nexmo.js:811:33)
    at IncomingMessage.emit (events.js:129:20)
    at IncomingMessage.wrapped (\node_modules\newrelic\lib\transaction\tracer\index.js:157:28)
    at IncomingMessage.wrappedEmit [as emit] (\node_modules\newrelic\lib\transaction\tracer\index.js:189:46)
    at _stream_readable.js:908:16
    at wrapped (\node_modules\newrelic\lib\transaction\tracer\index.js:157:28)
    at process._tickCallback (node.js:355:11)
[SyntaxError: Unexpected token <]
GET /test/nexmo/call 200 423.443 ms - 12
```

Code:
```javascript
router.get('/nexmo/call', function(req, res) {
	console.log("/test/nexmo/call has been initiated");

	var phoneNum = "+15555555555"; //Replacing my Real Number
	var dynamicMessage = "Hello World!";

	nexmo.sendTTSMessage({
			from: nexmoConfig.number,
			to: phoneNum,
			text: dynamicMessage,
			lg: 'en-gb',
			voice: 'female'
		}, function(error, response) {
			if (error) {
				console.log(error);
			} else {
				console.dir(response);
			}
			res.status(200).send({error: error});
		}
	);

	res.type('text/json');
});

router.get('/nexmo/sms', function(req, res) {
	console.log("/test/nexmo/sms has been initiated");
	
	var phoneNum = "+15555555555"; //Replacing my Real Number
	var dynamicSMS = "Hello World!";

	nexmo.sendSMSMessage({
			from: nexmoConfig.number,
			to: phoneNum,
			type: 'unicode',
			text: dynamicSMS
		}, function(error, response) {
			if (error) {
				console.log(error);
			} else {
				console.dir(response);
			}
			res.status(200).send({error: error});
		}
	);

	res.type('text/json');
});

```

**Comment by CalvertYang** [comment]
@taymoork2 Nexmo has changed the TTS message endpoint, I've already published an updated version package to [npm](https://www.npmjs.com/package/simple-nexmo).

Thanks for using this package :grinning:
